<Project>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- Позволяет запускать приложение, собранное под net8.0, на более новом рантайме. -->
    <RollForward>LatestMajor</RollForward>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Product>Мини-PDM: состав изделия</Product>
    <Company>АСКОН</Company>
  </PropertyGroup>

</Project>